experiment:
  name: "holt-winters"
  workdir: "/Users/mutlu.polatcan/"
  params:
    # --------------- MODEL PARAMS ------------
    data_path:
      - "../../example_datas/example_data.csv"
    train_data_percentage:
      range: [60,75,5]
    smoothing_level:
      range: [0.1,0.9,0.1]
    smoothing_slope:
      range: [0.1,0.9,0.1]
    damping_slope:
      range: [0.1,0.9,0.1]
    optimized:
      - true
      - false

slack:
  webhook_url: https://hooks.slack.com/services/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
  image_service:
    oauth:
      service_name: "flickr"
      client_key: "143c4dbc51405995b737767e8af69ca3"
      client_secret: "0717d06b5d55c123"
      access_token_path: "/Users/mutlu.polatcan/access_token.key"

mongodb:
  host: localhost
  port: 27017
  username: root
  password: admin


csv:
  status: "enabled"
  csv_format:
    separator: ","

debug: true
debug_traceback: false
