name: experiment_automator
version: 0.0.4
author: Mutlu Polatcan
author_email: mutlupolatcan@gmail.com
description: Experiment automator for ML
long_description_path: README.md
long_description_content_type: text/markdown
url: https://github.com/mpolatcan/experiment-automator
classifiers:
  - "Programming Language :: Python :: 3"
  - "License :: OSI Approved :: Apache Software License"
  - "Operating System :: OS Independent"
