# Experiment Automator config examples for statsmodels's Holt Winters
# Range type -> [(min,max,precision(number of values)]

experiment:
  name: "arima-experiment"
  workdir: "/Users/mutlu.polatcan/"
  params:
  # ------------- MODEL PARAMS --------------
    data_path:
      - "../../example_datas/example_data.csv"
    train_data_percentage:
      range: [60,75,5]
    arima_p_value:
      range: [1,5,1]
    arima_q_value:
      range: [1,5,1]
    arima_d_value:
      range: [1,2,1]
  # ------------- FIT PARAMS --------------


slack:
  webhook_url: https://hooks.slack.com/services/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
  image_service:
    oauth:
      name: "flickr"
      client_key: "143c4dbc51405995b737767e8af69ca3"
      client_secret: "0717d06b5d55c123"
      access_token_path: "/Users/mutlu.polatcan/access_token.key"

csv:
  status: "enabled"
  csv_format:
    separator: ","

# TODO Drive service settings will be updated
drive:

# Debug mode for development. It is not used in production.
debug: true
debug_traceback: false