# Experiment Automator config examples for statsmodels's Holt Winters
# Range type -> [(min,max,precision(number of values)]

experiment:
  name: "test-experiment"
  workdir: "/Users/mutlu.polatcan/"
  params:
    # ------------- MODEL PARAMS --------------
    trend:
      - "add"
      - "mul"
      - null
    seasonal:
      - "add"
      - "mul"
      - null
    seasonal_periods:
      range: [0.1,0.9,0.2]
  # ------------- FIT PARAMS --------------
    smoothing_level:
      range: [0.1,0.9,0.2]
    smoothing_slope:
      range: [0.1,0.9,0.2]
    smoothing_seasonal:
      range: [0.1,0.9,0.2]
    damping_slope:
      range: [0.1,0.9,0.2]
    optimized:
      - true
      - false
    use_box_cox:
      - true
      - false
    remove_bias:
      - true
      - false
    use_basinhopping:
      - true
      - false

#slack:
  webhook_url: https://hooks.slack.com/services/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
  notification_format:
    fail:
      pretext: "FAILED"
      title: "Test for Experiment Automator"
      text: "Test for Experiment Automator"
      color: "red"
      footer: "Experiment Automator"
      ts: true
    success:
      pretext: "SUCCESS"
      title: "Test for Experiment Automator"
      text: "Test"
      color: "green"
      footer: "Experiment Automator"
      ts: true


csv:
  status: "enabled"
  csv_format:
    separator: "-"
    columns:
      - "name"
      - "surname"
      - "use_basinhopping"

# TODO Drive service settings will be updated
drive:

# Debug mode for development. It is not used in production.
debug: true